DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS EVENT;

CREATE TABLE USERS(
    NAME VARCHAR(255),
    AGE INT,
    EMAIL VARCHAR(255) PRIMARY KEY
);

CREATE TABLE EVENT(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    START_DATE DATE,
    END_DATE DATE
);
